#!/bin/bash
### Job name
#PBS -N subset_py
### Project code
#PBS -A UUSL0032
#PBS -l walltime=06:00:00
#PBS -q main
### Merge output and error files
#PBS -j oe
#PBS -o subset.txt
### Select 1 nodes with 16 CPUs each for a total of 16 processes
#PBS -l select=1:ncpus=16
### Send email on abort, begin, and end
#PBS -m abe
#PBS -M cleveland.a.zac@gmail.com

### Change to directory from which job is submitted
cd $PBS_O_WORKDIR
### Activate conda environment

source activate mland_xr

### Run the executable
mpiexec_mpt -n 16 python -u ./subset_era5_data.py
